apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-api
  namespace: mlops-home-assignment
  labels:
    app: ai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      containers:
      - name: ai-api
        image: ghcr.io/jarnedemoen/mlops-ha-jarnedemoen-lungs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
          name: http
      # Pull secret credentials
      imagePullSecrets:
      - name: regcred
        