apiVersion: v1
kind: Service
metadata:
  name: ai-api
  namespace: mlops-home-assignment
  labels:
    app: ai-api
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ai-api